#!/bin/sh
#
# init.d script with LSB support.
#
# Developed for HTRC to start/stop Solr nodes running
# Loosely based on mongodb
#
# Copyright (c) 2007 Javier Fernandez-Sanguino <jfs@debian.org>
#
# This is free software; you may redistribute it and/or modify
# it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2,
# or (at your option) any later version.
#
# This is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License with
# the Debian operating system, in /usr/share/common-licenses/GPL;  if
# not, write to the Free Software Foundation, Inc., 59 Temple Place,
# Suite 330, Boston, MA 02111-1307 USA
#
### BEGIN INIT INFO
# Provides:          solrnodes7
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web-endpoints for nodes within a Solr Cluster
# Description:       Controls a set of Jetty based servlets that provide the
#                    end-points to the Solr nodes on this machine that
#                    operate in a larger Solr Cluster operating across several
#                    machines.  Use of a Replication Factor >=2 for Solr indexes
#                    means all the nodes running on a single machine can be brought
#                    down with it affecting the operation of the Solr cluster.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/HTRC-Solr-EF-Setup/HTRC-Solr-EF-Cloud/scripts/htrc-ef-solr7-cmd-on-this-host.sh 
DESC="HTRC Extracted Features"

# Default defaults.  Can be overridden by the /etc/default/$NAME
NAME=solrnodes7
ENABLE_SOLRNODES7=yes

# Include solrnodes7 defaults if available
if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi

if test ! -x $DAEMON; then
    echo "Could not find $DAEMON"
    exit 0
fi

if test "x$ENABLE_SOLRNODES7" != "xyes"; then
    exit 0
fi

. /lib/lsb/init-functions


DAEMONUSER=${DAEMONUSER:-www-data}

set -e

start_server() {
    sudo -u $DAEMONUSER $DAEMON start
    errcode=$?
    return $errcode
}

restart_server() {
    sudo -u $DAEMONUSER $DAEMON restart
    errcode=$?
    return $errcode
}

stop_server() {
    sudo -u $DAEMONUSER $DAEMON stop
    errcode=$?
    return $errcode
}


status_server() {
    sudo -u $DAEMONUSER $DAEMON status
    errcode=$?
    return $errcode
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC for" "$NAME"
        if start_server ; then
            log_end_msg 0
        else
            # Either we could not start it
            log_end_msg 1
        fi
	;;
  stop)
        log_daemon_msg "Stopping $DESC for" "$NAME"
        errcode=0
        stop_server || errcode=$?
        log_end_msg $errcode
        ;;
  restart)
        log_daemon_msg "Restarting $DESC for" "$NAME"
        errcode=0
        restart_server || errcode=$?
        log_end_msg $errcode
	;;
  status)
        log_daemon_msg "Checking status of $DESC for" "$NAME"
        errcode=0
        status_server || errcode=$?
        log_end_msg $errcode
        ;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0
